# Generated by Django 4.2.5 on 2023-09-20 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.DateTimeField(default=datetime.datetime(2023, 9, 20, 8, 17, 27, 710213, tzinfo=datetime.timezone.utc), help_text='Укажите время для отправки рассылки в формате: хх.хх.хххх хх:хх:хх', verbose_name='Время рассылки')),
                ('periodicity', models.IntegerField(choices=[(1, 'Раз в день'), (7, 'Раз в неделю'), (30, 'Раз в месяц')], default=1, verbose_name='Периодичность')),
                ('mailing_status', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('started', 'Запущена'), ('failed', 'Ошибка')], default='created', max_length=20, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MessageSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_subject', models.CharField(max_length=150, verbose_name='тема письма')),
                ('letter_body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
    ]
